### ISSUE TITLE
"LLM.tripinfo.xml" not found

### ISSUE THREAD

**Issue by DQNlearner** [Traffic-Alpha/iLLM-TSC#11]
Excuse me. I'm trying to running your iLLM-TSC project, but i can't find the "LLM.tripinfo.xml" profile which is used to init the environment. Is there some way to generate this file? Thank you.

**Comment by pangay** [comment]
The "LLM.tripinfo.xml" file is a simulation log file that records information about vehicles during the simulation process. When you run it, the filename may differ from “LLM,” so please look for other .tripinfo.xml file. It is automatically generated during runtime. Could you let me know where the error is occurring?

**Comment by DQNlearner** [comment]
Thank you very much for answering my question. I have found the "trip_info.xml" in /log folder. The current problem is when i try to run "rl_llm_tsc" file, there is a TypeError that make_env() got an unexpected keyword argument 'trip_info'. I think there is a bug in "rl_llm_tsc"'s "Init Env" part.

**Comment by pangay** [comment]
This may be due to changes in the version of tshub. You can try updating tshub, or you can comment out this parameter; this won’t affect the overall operation. Feel free to leave a message if you encounter any issues.

**Comment by DQNlearner** [comment]
OK. Thank you！
