### ISSUE TITLE
How to simulate training results

### ISSUE THREAD

**Issue by DJjiery** [Traffic-Alpha/iLLM-TSC#5]
I have used the training results of RL and RL+LLM respectively. How can I perform simulation?

**Comment by pangay** [comment]
What do you mean by 'simulation'? Are you referring to how to view the results? Do you need to install Sumo-gui, or could you describe your issue more clearly?

**Comment by DJjiery** [comment]
> What do you mean by 'simulation'? Are you referring to how to view the results? Do you need to install Sumo-gui, or could you describe your issue more clearly?
